name: sharding-repl-cache

services:
  configsrv:
    container_name: configsrv
    image: mongo:7
    command: ["mongod", "--configsvr", "--replSet", "configReplSet", "--bind_ip_all", "--port", "27019"]
    volumes:
      - configsrv_data:/data/db
    networks:
      - mongo-net

  shard1-1:
    container_name: shard1-1
    image: mongo:7
    command: ["mongod", "--shardsvr", "--replSet", "rs1", "--bind_ip_all", "--port", "27018"]
    volumes:
      - shard1_1_data:/data/db
    networks:
      - mongo-net

  shard1-2:
    container_name: shard1-2
    image: mongo:7
    command: ["mongod", "--shardsvr", "--replSet", "rs1", "--bind_ip_all", "--port", "27018"]
    volumes:
      - shard1_2_data:/data/db
    networks:
      - mongo-net

  shard1-3:
    container_name: shard1-3
    image: mongo:7
    command: ["mongod", "--shardsvr", "--replSet", "rs1", "--bind_ip_all", "--port", "27018"]
    volumes:
      - shard1_3_data:/data/db
    networks:
      - mongo-net

  shard2-1:
    container_name: shard2-1
    image: mongo:7
    command: ["mongod", "--shardsvr", "--replSet", "rs2", "--bind_ip_all", "--port", "27018"]
    volumes:
      - shard2_1_data:/data/db
    networks:
      - mongo-net

  shard2-2:
    container_name: shard2-2
    image: mongo:7
    command: ["mongod", "--shardsvr", "--replSet", "rs2", "--bind_ip_all", "--port", "27018"]
    volumes:
      - shard2_2_data:/data/db
    networks:
      - mongo-net

  shard2-3:
    container_name: shard2-3
    image: mongo:7
    command: ["mongod", "--shardsvr", "--replSet", "rs2", "--bind_ip_all", "--port", "27018"]
    volumes:
      - shard2_3_data:/data/db
    networks:
      - mongo-net

  mongos:
    container_name: mongos
    image: mongo:7
    command: ["mongos", "--configdb", "configReplSet/configsrv:27019", "--bind_ip_all", "--port", "27017"]
    depends_on:
      - configsrv
      - shard1-1
      - shard1-2
      - shard1-3
      - shard2-1
      - shard2-2
      - shard2-3
    networks:
      - mongo-net

  redis:
    container_name: redis
    image: redis:7-alpine
    networks:
      - mongo-net

  pymongo_api:
    container_name: pymongo_api
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - mongos
      - redis
    ports:
      - "8080:8080"
    environment:
      MONGODB_URL: "mongodb://mongos:27017"
      MONGODB_DATABASE_NAME: "somedb"
      REDIS_URL: "redis://redis:6379"
    networks:
      - mongo-net

volumes:
  configsrv_data:
  shard1_1_data:
  shard1_2_data:
  shard1_3_data:
  shard2_1_data:
  shard2_2_data:
  shard2_3_data:

networks:
  mongo-net:
    driver: bridge
